site_name: Ana Carolina Gomes

nav:
    - Home: index.md
    - Trajetória acadêmica: publications.md
    - Carreira em Tecnologia: tech.md
    
theme: 
  name: material
  language: pt-BR
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Montserrat
  features:
    - navigation.tabs
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer

plugins:
  - search:
      lang: pt

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/carol_gsv
    - icon:  fontawesome/brands/github
      link: https://github.com/lingsv

